require('plugins')

require('config.base')
require('config.treesitter')
require('config.lsp')
require('config.cmp')
require('config.gitsigns')
require('config.colorscheme')
require('config.lualine')
require('config.autopairs')
require('config.bufferline')
require('config.fzf')
require('config.oil')
