add_newline = false

[aws.region_aliases]
ap-northeast-1 = "jp"

[directory]
truncation_length = 100
truncate_to_repo = false

[package]
disabled = true

[time]
disabled = false

[ruby]
format = "| ruby [$version ]($style)"

[python]
format = "| python [$version ]($style)"

[nodejs]
format = "| node [$version ]($style)"

[golang]
format = "| golang [$version ]($style)"

[rust]
format = "| rust [$version ]($style)"

[lua]
format = "| lua [$version ]($style)"
